spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.shadowfiend.top:1992/nsa-security?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root@123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 0
      logic-not-delete-value: 1

cmii.auth:
  token:
    expireTime: 60
  encrypt:
    times: 12
    algorithmName: "MD5"